return {
  "hrsh7th/cmp-nvim-lsp",
  "L3MON4D3/LuaSnip",
  "hrsh7th/cmp-buffer",
  "hrsh7th/cmp-path",
  "hrsh7th/cmp-cmdline",
  "hrsh7th/cmp-vsnip",
  "hrsh7th/vim-vsnip",
  "saadparwaiz1/cmp_luasnip",
  "SirVer/ultisnips",
  "dcampos/nvim-snippy",
  "dcampos/cmp-snippy",
  "honza/vim-snippets",
  "hrsh7th/cmp-calc",
  "f3fora/cmp-spell",
  "tamago324/cmp-zsh",
  "hrsh7th/cmp-nvim-lsp-signature-help",
}
